Adding the week number parameter
JonnyWong16/plexpy pull request #1283
Opened 2018-04-10 10:05 UTC by samip5

I have now added the week number parameter and it uses the `arrow` library as suggested. The other edits that were suggested in #1282 are somewhat implemented like I did organize it better I hope.

I have tested that the newsletter works with the `week_number` in the body of it.

2018-04-10 15:08 UTC, JonnyWong16 requested changes
Changes below.

2018-04-10 15:08 UTC, JonnyWong16 commented on plexpy/common.py
> +            {'name': 'Week Number', 'type': 'int', 'value': 'week_number', 'description': 'The week number of current week.'},
Move after "End Date".

2018-04-10 15:08 UTC, JonnyWong16 commented on plexpy/newsletters.py
> +    def __init__(self, config=None, email_config=None, start_date=None, week_number=None, end_date=None,
Doesn't need to be a class attribute.

2018-04-10 15:08 UTC, JonnyWong16 commented on plexpy/newsletters.py
> +            'week_number': self.week_number,
```python
'week_number': self.start_date.isocalendar()[1]
```

2018-04-10 15:08 UTC, JonnyWong16 commented on plexpy/newsletters.py
> +        self.week_number = None
Remove.

2018-04-10 15:08 UTC, JonnyWong16 commented on plexpy/newsletters.py
> +        if week_number is None:
Remove.

2018-04-10 17:10 UTC, samip5 reviewed
I have now done the suggested edits and updated the branch.

2018-04-11 03:16 UTC, JonnyWong16 approved these changes

2018-04-11 03:16 UTC, JonnyWong16 commented
Thanks.

2018-04-11 03:17 UTC, merged