Added "silent_message" option for Telegram Agent
JonnyWong16/plexpy pull request #1377
Opened 2020-08-21 20:55 UTC by JohnnyKing94

I opened a feature request (https://feathub.com/Tautulli/Tautulli/+444) this morning, then I tried to implement this on my own and it works. So I added a new checkbox in the notification telegram config in order to send new messages silently. The telegram users will receive a notification with no sound. In this way I can use the bot to spam non-important messages in the group (like watched notifications, play notification etc) without alerting everytime anyone.

2020-08-23 09:34 UTC, agneevX requested changes

2020-08-25 03:22 UTC, JonnyWong16 requested changes

2020-08-25 03:22 UTC, JonnyWong16 commented on plexpy/notifiers.py
> +                          'description': 'Sends the message silently. Users will receive a notification with no sound.',
"`Send notifications silently without any alert sounds.`"

2020-08-25 03:22 UTC, JonnyWong16 commented on plexpy/notifiers.py
> +        if self.config['silent_message']:
Just add the one line above.
```py
                if len(text) > 1024:
                    data['disable_notification'] = True
                else:
                    data['caption'] = text.encode('utf-8')
                    data['disable_notification'] = bool(self.config['silent_notification'])      
```

2020-08-25 03:22 UTC, JonnyWong16 commented on plexpy/notifiers.py
> +                       'silent_message': 0,
Rename the setting to `silent_notification`.

2020-08-25 03:22 UTC, JonnyWong16 commented on plexpy/notifiers.py
> +                         {'label': 'Enable Silent Messages',
"`Enable Silent Notifications`"

2020-09-11 07:43 UTC, agneevX commented
Any progress on this @JohnnyKing94?

2020-09-14 10:49 UTC, JohnnyKing94 reviewed
Sorry for the long waiting... now everything has been adressed and tested... you can also try and let me know

2020-09-14 18:07 UTC, JonnyWong16 commented
Please also implement the wording changes I requested above.

2020-09-14 18:27 UTC, JohnnyKing94 commented
Done. :)

2020-09-14 18:31 UTC, JonnyWong16 commented
There is one more change. Rename `silent_message` to `silent_notification`.

2020-09-14 18:47 UTC, JohnnyKing94 commented
Done that too. 😄 😃

2020-09-27 01:44 UTC, JonnyWong16 approved these changes

2020-09-27 01:44 UTC, JonnyWong16 commented
Looks like everything works. Thanks.

2020-09-27 01:44 UTC, merged