Bump thread pool to 100
JonnyWong16/plexpy pull request #1425
Opened 2021-05-01 02:55 UTC by psaab

Thread pool of 10 is way too small for large servers

## Description

This fixes quite a lot of http accept stalls due to lack of resources.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code

2021-05-02 12:41 UTC, StarSmasher44 commented
I am far from related to any of this, but is 10x not a unreasonably high upgrade? Especially for those that may have weak to terrible CPUs. I wouldn't know how far this can eat away at performance but possibly a x5 increase would see the same benefit without the potential to break someone's processor or anything else that runs on there.

2021-05-02 21:00 UTC, JonnyWong16 commented
100 is excessive. Make it a hidden advanced setting `HTTP_THREAD_POOL` in the config file and leave the default at 10. Then you can change it yourself.

2021-05-03 16:38 UTC, psaab commented
Ok I moved it to a config setting

2021-05-03 16:41 UTC, JonnyWong16 requested changes

2021-05-03 16:41 UTC, JonnyWong16 commented on plexpy/config.py
> +    'THREAD_POOL': (int, 'General', 10),
Rename to `HTTP_THREAD_POOL`.

2021-05-03 17:14 UTC, psaab commented
Changed

2021-05-03 17:16 UTC, JonnyWong16 commented
... but also move it so it is with the other `HTTP_` settings.

2021-05-03 17:17 UTC, psaab commented
Whoops, sorry..

2021-05-03 17:18 UTC, psaab commented
ok, i think this is correct now

2021-05-03 17:19 UTC, psaab commented on plexpy/config.py
> +    'THREAD_POOL': (int, 'General', 10),
done

2021-05-03 17:19 UTC, JonnyWong16 approved these changes

2021-05-03 17:20 UTC, JonnyWong16 commented
Thanks.

2021-05-03 17:20 UTC, merged