MQTT improvements
JonnyWong16/plexpy pull request #1767
Opened 2022-06-15 21:40 UTC by ccutrer

## Description

(re-open of #1424)

This is a series of changes to improve the machine readability of notifications sent via MQTT. In particular, being able to send to multiple topics based on any parameter (i.e. I plan to include the {player_id} in the topic so that if I want to do automations for what's happening in a particular room, I only have to subscribe to that topic), and being able to either send bare
text not wrapped in JSON for simpler handling at the recipient OR being able to build a full JSON object with proper escaping to bundle a lot of information in a single notification.

### Issues Fixed or Closed

Fixes https://github.com/Tautulli/Tautulli/issues/1415 and https://github.com/Tautulli/Tautulli/issues/1416.

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the docstring for new or existing methods

2022-07-03 22:19 UTC, JonnyWong16 requested changes
The combinations of the two options "Include Subject" and "Send Message as JSON" do not behave as expected.

| Include Subject | As JSON | Subject                   | Body                                 | MQTT Payload                                                                                                             |                              |
|-----------------|---------|---------------------------|--------------------------------------|--------------------------------------------------------------------------------------------------------------------------|------------------------------|
| Yes             | No      | `Tautulli`                | `Test Notification`                  | `{"subject": "Tautulli", "body": "Test   Notification", "topic": "testtopic/1"}`                                         | :heavy_check_mark:           |
| Yes             | No      | `{"title": "Tautulli"}`   | `{"message": "Test Notification"}`   | `{"subject": "{\"title\"}",   "body": "{\"message\"}", "topic":   "testtopic/1"}`                                        | :heavy_check_mark:           |
| Yes             | No      | `{{"title": "Tautulli"}}` | `{{"message": "Test Notification"}}` | `{"subject": "{\"title\":   \"Tautulli\"}", "body":   "{\"message\": \"Test Notification\"}",   "topic": "testtopic/1"}` | :heavy_check_mark:           |
| Yes             | Yes     | `Tautulli`                | `Test Notification`                  | Error: unable to parse JSON                                                                                              | :heavy_check_mark:           |
| Yes             | Yes     | `{"title": "Tautulli"}`   | `{"message": "Test Notification"}`   | `{"subject": "{\"title\":   \"Tautulli\"}", "body":   "{\"message\": \"Test Notification\"}",   "topic": "testtopic/1"}` | :x: Should be unescaped JSON |
| Yes             | Yes     | `{{"title": "Tautulli"}}` | `{{"message": "Test Notification"}}` | Error: unable to parse JSON                                                                                              | :heavy_check_mark:           |
| No              | Yes     | `Tautulli`                | `Test Notification`                  | Error: unable to parse JSON                                                                                              | :heavy_check_mark:           |
| No              | Yes     | `{"title": "Tautulli"}`   | `{"message": "Test Notification"}`   | `{"message":   "Test Notification"}`                                                                                     | :heavy_check_mark:           |
| No              | Yes     | `{{"title": "Tautulli"}}` | `{{"message": "Test Notification"}}` | Error: unable to parse JSON                                                                                              | :heavy_check_mark:           |
| No              | No      | `Tautulli`                | `Test Notification`                  | `Test Notification`                                                                                                      | :x: Should be escaped string |
| No              | No      | `{"title": "Tautulli"}`   | `{"message": "Test Notification"}`   | `{"message"}`                                                                                                            | :x: Should be escaped string |
| No              | No      | `{{"title": "Tautulli"}}` | `{{"message": "Test Notification"}}` | `{"message":   "Test Notification"}`                                                                                     | :x: Should be escaped string |

I believe my suggested changes fixes that.

2022-07-03 22:19 UTC, JonnyWong16 commented on plexpy/notification_handler.py
> +                                                       as_json=notifier_config['config']['as_json'])
This breaks all other notification agents.

```
KeyError: 'as_json'
```

```suggestion
                                                       as_json=notifier_config['config'].get('as_json', False))
```

2022-07-03 22:19 UTC, JonnyWong16 commented on plexpy/notifiers.py
> +    def agent_notify(self, subject='', body='', action='', parameters={}, **kwargs):
Don't change the method signature.

```suggestion
    def agent_notify(self, subject='', body='', action='', **kwargs):
```

2022-07-03 22:19 UTC, JonnyWong16 commented on plexpy/notifiers.py
> +        topic = topic.format(**parameters)
```suggestion
        topic = topic.format(**kwargs.get('parameters', {}))
```

2022-07-03 22:19 UTC, JonnyWong16 commented on plexpy/notifiers.py
> +                                         'be sent as the bare payload, with no additional escaping.',
> with no additional escaping.

That's not true. Escaping depends on the `as_json` option.

```suggestion
                          'description': 'Include the subject in the MQTT payload. '
                                         'The default is to wrap the notification subject and body into a single payload. '
                                         'Uncheck to only send the notification body as the bare payload.',
```

2022-07-03 22:19 UTC, JonnyWong16 commented on plexpy/notification_handler.py
> +    elif agent_id == 25 or as_json:
Logger messages below still say "webhook". Format the logger messages with the correct agent.

```py
agent = 'MQTT' if agent_id == 23 else 'webhook'
```
```py
logger.error("Tautulli NotificationHandler :: Unable to parse custom %s json header data: %s. Using fallback." % (agent, e))
```

2022-07-03 22:19 UTC, JonnyWong16 commented on plexpy/notifiers.py
> +            data = body
```suggestion
        if self.config['as_json']:
            subject = json.loads(subject)
            body = json.loads(body)

        if self.config['incl_subject']:
            data = {'subject': subject,
                    'body': body,
                    'topic': topic}
        else:
            data = body
```

2022-07-03 22:19 UTC, JonnyWong16 commented on plexpy/notifiers.py
> +            topic, payload=data, qos=self.config['qos'], retain=bool(self.config['retain']),
Still need `json.dumps`

```suggestion
            topic, payload=json.dumps(data), qos=self.config['qos'], retain=bool(self.config['retain']),
```

2022-07-14 18:14 UTC, ccutrer commented
> The combinations of the two options "Include Subject" and "Send Message as JSON" do not behave as expected.
> 
> Include Subject	As JSON	Subject	Body	MQTT Payload	
> No	No	`Tautulli`	`Test Notification`	`Test Notification`	❌ Should be escaped string

Why should this end up as a quoted string?? The point of not including the subject and having a "bare" payload is so that the recipient _doesn't_ have to parse as JSON.

2022-07-14 18:25 UTC, JonnyWong16 commented
Because "As Json" is unchecked. Settings should control independent things. "Include Subject" should have no control over JSON at all.

2022-07-14 18:26 UTC, ccutrer commented
Exactly. As JSON is unchecked. So don't treat the body as JSON at all. Just send it through.

2022-07-14 18:28 UTC, JonnyWong16 commented
No treating as JSON is an escaped string.

2022-07-14 18:29 UTC, ccutrer commented
That doesn't make any sense. As evidenced by all the questions about your as_json option. Obviously we're not going to agree. Feel free to modify as you see fit, but I'm no longer interested in debating differing opinions here.

2022-07-14 18:29 UTC, closed without merging