Small example of making a request using curl
JonnyWong16/plexpy pull request #951
Opened 2017-01-23 05:14 UTC by hamiltont

Not sure if this is useful enough to be included, but it would have saved me about 2min since i thought the API was POST-only

2017-01-23 05:14 UTC, hamiltont commented
ps - targeted dev branch. Is that correct?

2017-01-23 22:43 UTC, Arcanemagus requested changes

2017-01-23 22:43 UTC, Arcanemagus commented on API.md
> +Making a request to PlayPy using the [curl](https://curl.haxx.se/) tool is straightforward
* `PlayPy` -> `PlexPy`
* Put a `:` at the end of the line

2017-01-23 22:43 UTC, Arcanemagus commented on API.md
> +```
If you set the language to `ShellSession` it will do some highlighting for you:

\`\`\`ShellSession

2017-01-23 22:43 UTC, Arcanemagus commented on API.md
> +your_name$ curl "http://<hostname>:<port>/api/v2?apikey=<apikey>&cmd=get_home_stats"  \
The `your_name` is implied from the `$`, no need to include it.

2017-01-23 23:15 UTC, Hellowlol commented
There shouldn't be any direct pulls to the API md. The page is made by the API.

2017-01-24 00:54 UTC, hamiltont commented
oop, good call @Hellowlol . I'll just close this PR and may open a new one later on that file

2017-01-24 00:54 UTC, closed without merging